PALETTE = {
    "bg_top": "#fdf9fc",
    "bg_bottom": "#f6edf2",
    "blob_1": "#f5dce7",
    "blob_2": "#f5ecd8",
    "blob_3": "#ece3f5",
    "card": "#fffdfd",
    "card_edge": "#eadde5",
    "card_glass": "#fff8fb",
    "text": "#352a33",
    "muted": "#7b7179",
    "primary": "#ead1dc",
    "primary_hover": "#e3c2d1",
    "primary_soft": "#f8eef3",
    "secondary": "#ffffff",
    "secondary_hover": "#faf4f7",
    "success": "#74a88f",
    "danger": "#bc7f95",
    "field": "#fffefe",
    "field_border": "#e7dbe2",
    "field_focus": "#d8b8c7",
    "pill": "#f7f0f4",
    "shadow": "#eadbe3",
    "glass": "#fdf7fa",
    "glass_border": "#efe2e8",
    "progress_bg": "#f2e9ef",
    "progress_fill": "#d9b3c5",
    "locked": "#efe8ec",
    "completed": "#e2e0e4",
}

FONT = "Helvetica"